### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by hanserasmus** [cblopez/nmapthon#3]
Hi. Thank you for this great tool. I tried to include this in a python program I am trying to write, but it seems the module is not actually installed. Running pip install and even pip3 install, shows the module when you run `pip list`. But, the __init__.py files etc are not created and therefore the module cannot be imported. Any ideas?

**Comment by cblopez** [comment]
Hi! The new update solves the pip installation issue and adds some new stuff. Hope you enjoy it and thanks for commenting the issue
